/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secure.pos;

import invoices.Invoice;
import invoices.InvoiceDAOImpl;
import items.Item;
import items.ItemDAOImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import products.Product;
import products.ProductDAOImpl;
import users.User;

/**
 *
 * @author fernandoenad
 */
public class CashierGUI extends javax.swing.JFrame {
    private User loggedUser = null;
    private Invoice newInvoice = null;
    InvoiceDAOImpl invoiceDAOImpl = new InvoiceDAOImpl();
    ProductDAOImpl productDAOImpl = new ProductDAOImpl();
    ItemDAOImpl itemDAOImpl = new ItemDAOImpl();
    
    /**
     * Creates new form CashierGUI
     */
    public CashierGUI() {
        initComponents();
        login();
    }
    
    public void login(){
        //this.loggedUser = new User(1, "cashier", "cashier", "Cashier");
        CashierLoginGUI cashierloginGUI = new CashierLoginGUI(this, true);
        cashierloginGUI.show(true);
        this.loggedUser = cashierloginGUI.getUser();
        
        new_invoice();
    }
    
    public void new_invoice(){
        DefaultTableModel model = (DefaultTableModel) itemsTBL.getModel();
        model.setRowCount(0);
        barcodeTF.setText("");
        barcodeTF.grabFocus();
        close_saleBTN.setEnabled(false);
        total_costLBL.setText("0.00");
        amt_paidTF.setText("0.00");
        changeLBL.setText("0.00");
        
        this.newInvoice = new Invoice(0, 0, 0.00, 0.00, 0.00, this.loggedUser.getUser_id(), "Pending", "");
        
        if(invoiceDAOImpl.create(this.newInvoice) == true){
            this.newInvoice = invoiceDAOImpl.read_last_insert(this.loggedUser.getUser_id());
            loggedUsernameLBL.setText("Cashier: " + this.loggedUser.getUsername());
            invoice_noLBL.setText("Invoice No.: " + this.newInvoice.getInvoice_id());
            total_quantityLBL.setText("Total Quantity: " + this.newInvoice.getTotal_quantity());
        } else {
            JOptionPane.showMessageDialog(null, "Error was encountered!", "Message", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barcodeTF = new javax.swing.JTextField();
        close_saleBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTBL = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        total_costLBL = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        changeLBL = new javax.swing.JLabel();
        amt_paidTF = new javax.swing.JTextField();
        invoice_noLBL = new javax.swing.JLabel();
        total_quantityLBL = new javax.swing.JLabel();
        loggedUsernameLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FBE POS v1.0 | Cashier");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Barcode:");

        barcodeTF.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        barcodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeTFActionPerformed(evt);
            }
        });

        close_saleBTN.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        close_saleBTN.setText("Close Sale");
        close_saleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_saleBTNActionPerformed(evt);
            }
        });

        itemsTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemsTBL);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Transaction"));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Total Cost:");

        total_costLBL.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        total_costLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total_costLBL.setText("0.00");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Amount Paid:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Change:");

        changeLBL.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        changeLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        changeLBL.setText("0.00");

        amt_paidTF.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        amt_paidTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        amt_paidTF.setText("0.00");
        amt_paidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amt_paidTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amt_paidTF)
                    .addComponent(total_costLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_costLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amt_paidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        invoice_noLBL.setText("Invoice No.: xxx");

        total_quantityLBL.setText("Total Quantity: xxx");

        loggedUsernameLBL.setText("Cashier: xxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invoice_noLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_quantityLBL))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(close_saleBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(loggedUsernameLBL))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close_saleBTN)
                    .addComponent(barcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoice_noLBL)
                    .addComponent(total_quantityLBL)
                    .addComponent(loggedUsernameLBL))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barcodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeTFActionPerformed
        // TODO add your handling code here:
        int product_id = Integer.parseInt(barcodeTF.getText());
        Product product = productDAOImpl.read_one(product_id);
        
        if(product != null){
            
            DefaultTableModel model = (DefaultTableModel) itemsTBL.getModel();
            
            model.addRow(new Object[]{
                product.getProduct_id(),
                product.getName(),
                1,
                String.format("%.2f", product.getPrice())
            });
            
            total_quantityLBL.setText("Quantity: " + model.getRowCount());
            double total_cost = Double.parseDouble(total_costLBL.getText());
            total_costLBL.setText(String.format("%.2f", total_cost + product.getPrice()));
            close_saleBTN.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Product not found!", "Message", JOptionPane.WARNING_MESSAGE);
        }
        
        barcodeTF.setText("");
    }//GEN-LAST:event_barcodeTFActionPerformed

    private void close_saleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_saleBTNActionPerformed
        // TODO add your handling code here:
        close_saleBTN.setEnabled(false);
        amt_paidTF.setText("");
        amt_paidTF.grabFocus();
    }//GEN-LAST:event_close_saleBTNActionPerformed

    private void amt_paidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amt_paidTFActionPerformed
        // TODO add your handling code here:
        double total_cost = Double.parseDouble(total_costLBL.getText());
        double amt_paid = Double.parseDouble(amt_paidTF.getText());
        amt_paidTF.setText(String.format("%.2f", amt_paid));
        double change = amt_paid - total_cost;
        changeLBL.setText(String.format("%.2f", change));
        
        if(change > 0){
            JOptionPane.showMessageDialog(null, "Printing receipt... Click OK to start a new transaction!", "Message", JOptionPane.INFORMATION_MESSAGE);
            this.newInvoice.setTotal_cost(total_cost);
            this.newInvoice.setAmt_paid(amt_paid);
            this.newInvoice.setChange(change);
            this.newInvoice.setStatus("Completed");

            if(invoiceDAOImpl.update(this.newInvoice.getInvoice_id(), this.newInvoice)){
                DefaultTableModel model = (DefaultTableModel) itemsTBL.getModel();

                for (int row = 0; row < model.getRowCount(); row++) {
                    for (int col = 0; col < model.getColumnCount(); col++) {
                        int product_id = Integer.parseInt(model.getValueAt(row, 0).toString()); 
                        int quantity = Integer.parseInt(model.getValueAt(row, 2).toString()); 
                        Item item = new Item(0, this.newInvoice.getInvoice_id(), product_id, quantity);
                        
                        if(itemDAOImpl.create(item) == false){
                            JOptionPane.showMessageDialog(null, "Error encountered!", "Message", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                }
                
                new_invoice();
            } else {
                JOptionPane.showMessageDialog(null, "Error encountered!", "Message", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Insufficient Payment!", "Message", JOptionPane.WARNING_MESSAGE);
            amt_paidTF.selectAll();
        }
        
    }//GEN-LAST:event_amt_paidTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt_paidTF;
    private javax.swing.JTextField barcodeTF;
    private javax.swing.JLabel changeLBL;
    private javax.swing.JButton close_saleBTN;
    private javax.swing.JLabel invoice_noLBL;
    private javax.swing.JTable itemsTBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loggedUsernameLBL;
    private javax.swing.JLabel total_costLBL;
    private javax.swing.JLabel total_quantityLBL;
    // End of variables declaration//GEN-END:variables
}
